feat(passmenu): reworked passmenu
I ruined the elegance of the original passmenu, but I did add the
feature of being able to select the kind of field you want to copy, be
it password, username or email etc., based on the password
file structure convention as explained by the creator of `pass`.

Basically, it sends a list of options to dmenu, and stores the return
value in a variable. It then uses `awk` with ': ' (note the space) as a
field separator, and prints the value where the field matches the
variable.

It also spawns a subprocess that will empty the clipboard again. This
should be decently robust, as I took it largely from the original `pass`
source.

diff --git a/passmenu b/passmenu
--- a/passmenu
+++ b/passmenu
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 
+set -o errexit  # abort on nonzero exitstatus
+set -o pipefail # don't hide errors within pipes
+
 shopt -s nullglob globstar
+
+clip_time="${PASSWORD_STORE_CLIP_TIME:-45}"
 
 if [[ -n $WAYLAND_DISPLAY ]]; then
 	dmenu='dmenu-wl'
@@ -12,18 +17,51 @@ else
 fi
 
 prefix=${PASSWORD_STORE_DIR-~/.password-store}
-password_files=( "$prefix"/**/*.gpg )
-password_files=( "${password_files[@]#"$prefix"/}" )
-password_files=( "${password_files[@]%.gpg}" )
+password_files=("$prefix"/**/*.gpg)
+password_files=("${password_files[@]#"$prefix"/}")
+password_files=("${password_files[@]%.gpg}")
 
 password_file=$(printf '%s\n' "${password_files[@]}" | "$dmenu" -c "$@")
 
 [[ -n $password_file ]] || exit
 
-gpg_is_cached=$(gpg-connect-agent 'keyinfo --list' /bye 2>/dev/null | awk '{if($7==1){print 1}}')
+field_name=$(
+	cat <<EOF | "$dmenu" -c
+password
+username
+email
+app password
+URL
+cancel
+EOF
+)
 
-if [[ $gpg_is_cached == 1 ]]; then
-    pass show -c "$password_file" 2>/dev/null
-else
-    st -c 'term-float' -T 'pass pin entry' -g 68x13 -e pass show -c "$password_file" 2>/dev/null && pass show -c "$password_file" 2>/dev/null
+[[ $field_name == 'cancel' ]] && exit
+
+gpg_is_cached=$(gpg-connect-agent 'keyinfo --list' /bye 2>/dev/null | awk '{ if ($7==1) { print 1 } }')
+
+if [[ $gpg_is_cached -ne 1 ]]; then
+	st -c 'term-float' -T 'pass pin entry' -g 68x13 -e pass -c "$password_file" 2>/dev/null
 fi
+
+if [[ $field_name == 'password' ]]; then
+	pass -c "$password_file" 2>/dev/null
+	exit
+fi
+
+secret="$(
+	pass "$password_file" |
+		awk -F ': ' -v field="$field_name" \
+			'BEGIN {IGNORECASE = 1} $1 == field { print $2 }'
+)"
+
+[[ -n $secret ]] || exit
+
+sleep_process_title="passmenu sleep"
+pkill -f "^$sleep_process_title" 2>/dev/null && sleep 0.5
+printf '%s' "$secret" | xclip -r -selection 'clipboard' &&
+	(
+		(exec -a "$sleep_process_title" bash <<<"trap 'kill %1' TERM; sleep '$clip_time' & wait")
+		xclip -selection 'clipboard' -i /dev/null
+	) >/dev/null 2>&1 &
+disown
