!feat: reuse existing gpg through `keychain`

diff --git a/passmenu_custom b/passmenu_custom
--- a/passmenu_custom
+++ b/passmenu_custom
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-set -o errexit  # abort on nonzero exitstatus
+set -o errexit  # abort on nonzero exit status
 set -o pipefail # don't hide errors within pipes
 
 shopt -s nullglob globstar
@@ -38,7 +38,11 @@ EOF
 
 [[ $field_name == 'cancel' ]] && exit
 
-gpg_is_cached=$(gpg-connect-agent 'keyinfo --list' /bye 2>/dev/null | awk '{ if ($7==1) { print 1 } }')
+eval "$(keychain --dir "$XDG_STATE_HOME/keychain" --quiet --noask --eval --agents 'gpg' 'secretray')"
+
+gpg_is_cached="$(
+	gpg-connect-agent 'keyinfo --list' /bye 2>/dev/null | awk '{ if ($7==1) { print 1 } }'
+)"
 
 if [[ $gpg_is_cached -ne 1 ]]; then
 	st -c 'term-float' -T 'pass pin entry' -g 68x13 -e pass -c "$password_file" 2>/dev/null
@@ -57,8 +61,8 @@ secret="$(
 
 [[ -n $secret ]] || exit
 
-sleep_process_title="passmenu sleep"
-pkill -f "^$sleep_process_title" 2>/dev/null && sleep 0.5
+sleep_process_title='passmenu sleep'
+pkill -x "$sleep_process_title" 2>/dev/null && sleep 0.5
 printf '%s' "$secret" | xclip -r -selection 'clipboard' &&
 	(
 		(exec -a "$sleep_process_title" bash <<<"trap 'kill %1' TERM; sleep '$clip_time' & wait")
